version: '3'
services:
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - payment-service
      - inventory-service
      - shipping-service

  payment-service:
    build: ./services/payment-service
    ports:
      - "3001:3001"

  inventory-service:
    build: ./services/inventory-service
    ports:
      - "3002:3002"

  shipping-service:
    build: ./services/shipping-service
    ports:
      - "3003:3003"