version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"   # Mở cổng 6379
    volumes:
      - redis-data:/data  # Dữ liệu Redis sẽ được lưu vào volume
    restart: always

volumes:
  redis-data:
    driver: local
